# Generated by Django 6.0.3 on 2026-03-22 16:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='staff',
        ),
        migrations.AlterModelManagers(
            name='staff',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='is_Manager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GeneralStaff',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
