# Generated by Django 6.0.3 on 2026-05-09 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_created_on_staff_last_edit_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
