# Generated by Django 6.0.3 on 2026-06-10 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 6, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
    ]
