# Generated by Django 6.0.3 on 2026-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollementstatus',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
