# Generated by Django 6.0.3 on 2026-05-07 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_alter_enrollementstatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 7, 22, 38, 41, 359622)),
        ),
    ]
