# Generated by Django 6.0.3 on 2026-05-07 20:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_lesson_lesson_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollement',
            old_name='lessons',
            new_name='num_of_lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='enrollment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_items', to='learner.enrollement'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
