# Generated by Django 6.0.3 on 2026-05-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_rename_lessons_enrollement_num_of_lessons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Learner',
            new_name='learner',
        ),
    ]
