# Generated by Django 6.0.3 on 2026-05-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0005_rename_learner_lesson_learner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='creted_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='learner',
        ),
    ]
