# Generated by Django 6.0.3 on 2026-05-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0006_rename_creted_by_lesson_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='phoneNumber',
            field=models.CharField(blank=True, default='070000000', max_length=12, null=True),
        ),
    ]
